### ISSUE TITLE
USER STORY: Social Media Sign Up

### ISSUE THREAD

**Issue by alexandrearantes1** [alexandrearantes1/love-running#6]
In order to **post on polls** as a **user**, I can **login using my social media accounts.**.

# Acceptance Criteria
a. The user can login using Google, Facebook or Twitter account.
b. The user still have the option to vote anonymously.
c. User can log off at any time.

# Tasks
- [ ] Create a Database to store user's data. 
- [ ] Create a login screen / window to allow users to use their Social Media accounts. 
- [ ] Identify the user and make it clear wether they are voting anonymously or not.
