### ISSUE TITLE
USER STORY: SMS Reminder

### ISSUE THREAD

**Issue by alexandrearantes1** [alexandrearantes1/love-running#7]
In order to **not miss the event** as a **user**, I can **provide my mobile number to receive an SMS message 1h before the event takes begins**.

# Acceptance Criteria
a. User can provide their phone number to be reminded of an specific event. 
b. The user will receive an SMS reminder 1h before the event takes place. 
c. User can unsubscribe to the event at any time if they choose to do so. 

# Tasks
- [ ] Create a form in each event's page to allow the user to submit their phone number. 
- [ ] Perform a simple validation to make sure the data entered is valid. 
- [ ] Store user's phone number associated with that event in order to send the SMS when the event is due. 
- [ ] Provide the user with the ability to cancel their subscription at an time.
