### ISSUE TITLE
USER STORY: Login with Social Media

### ISSUE THREAD

**Issue by alexandrearantes1** [alexandrearantes1/love-running#8]
In order to **vote on polls** as a **user**, I can **login using social media buttons**.

# Acceptance Criteria
a. When the user tries to vote on a poll, if not logged in, he is presented with the option to login with social media accounts
b. User clicks on the social media they would like to use. 
c. User is redirected to the screen that he was before logging in.

# Tasks
- [ ] Create a user database.
- [ ] Create the social media login screen.
- [ ] Display a "log off" button at the top right corner of the screen if the user is logged in.
